

services:
  # Название нашего сервиса (может быть любым)
  timer-app:
    # Говорим Docker Compose собрать образ на основе Dockerfile в текущей папке
    build: .
    # Имя, которое получит запущенный контейнер
    container_name: focus_timer_container
    # Пробрасываем порты (внешний_порт_ПК : внутренний_порт_Nginx)
    ports:
      - "8080:80"
    # Перезапускать контейнер автоматически, если он упал с ошибкой
    restart: always